##{PropertiesConnector} savedBy=jason, saveDate=Tue Sep 29 19:47:47 CDT 2026
ldapAdminDN=
ldapAdminPwd=
ldapSearchBase_people=ou=People, dc=example,dc=com
ldapSearchBase_group=ou=Groups, dc=example,dc=com
ldapUrl=ldap://localhost:389
